root = "."
tmp_dir = ".\\tmp"

[build]
  cmd = "go build -o .\\tmp\\main.exe .\\cmd"
  bin = ".\\tmp\\main.exe"
  full_bin = ".\\tmp\\main.exe"
  
  
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  stop_on_error = false

[color]
  main = "magenta"
  build = "yellow"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
